#!/usr/bin/env bash
# Create a script to install and config HAProxy on lb-01 server
# Config HAProxy to send traffic to web-01 and web-02 servers
# Distrib requests using roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and config HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  hhaggai-frontend
        bind *:80
        mode http
        default_backend hhaggai-backend
backend hhaggai-backend
        balance roundrobin
        server check
        server check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
