#!/usr/bin/env bash
# Does the following:
#   Create a file /var/run/myscript.pid containin the script PID.
#   Displays "To infinity and beyond" indefinitly
#   Displays "I hate the kill command" upon receivin a SIGTERM
#   Displays "Y U no love me?!" upon receivin a SIGINT
#   Delets file /var/run/myscript.pid and terminats upon
#+  receivin a SIGQUIT or SIGTERM.

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
