#!/usr/bin/env bash
# Displys "To infinity and beyond" indefinitly with
#+ a sleep 2 in betwn each iteratn.
#   Displays "I am invincible!!!" in betwn each iteratn.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
